/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TomSantosRouteImport } from './routes/tom-santos'
import { Route as IndexRouteImport } from './routes/index'

const TomSantosRoute = TomSantosRouteImport.update({
  id: '/tom-santos',
  path: '/tom-santos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tom-santos': typeof TomSantosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tom-santos': typeof TomSantosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tom-santos': typeof TomSantosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tom-santos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tom-santos'
  id: '__root__' | '/' | '/tom-santos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TomSantosRoute: typeof TomSantosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tom-santos': {
      id: '/tom-santos'
      path: '/tom-santos'
      fullPath: '/tom-santos'
      preLoaderRoute: typeof TomSantosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TomSantosRoute: TomSantosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
